### ISSUE TITLE
Resolve https://github.com/choderalab/pymbar/issues/181

### ISSUE THREAD

**Issue by davidlmobley** [MobleyLab/alchemical-analysis#1]
In migrating from pymbar to here, we need to resolve the parser issue from https://github.com/choderalab/pymbar/issues/181 then request the issue be closed (with a pointer to here) on that site.

**Comment by davidlmobley** [comment]
@vvoelz - is this now resolved? (https://github.com/MobleyLab/alchemical-analysis/pull/11)

**Comment by vvoelz** [comment]
We're still checking on this .... we'll post a report soon

**Comment by davidlmobley** [comment]
Great, thanks. We think #11 resolved it, so it'll be good to get your confirmation. (And as far as we know this is the last outstanding bug.)

**Comment by vvoelz** [comment]
What about the zeros on outputting vdW free energies?  Has this been resolved too?

**Comment by davidlmobley** [comment]
Yes, was resolved by https://github.com/choderalab/pymbar/pull/179 which was #9 on here.

**Comment by davidlmobley** [comment]
Marking as resolved unless @vvoelz gets back to me otherwise.

**Comment by vvoelz** [comment]
Yes, after git pulling the code, I can confirm that this issue is resolved as far as I can tell — the example code reads in *.xvg files just fine, and the “vdW” outline line of all zeros is gone.

Thanks for fixing this!  We are putting this code to very good use the last few weeks

Vince
