### ISSUE TITLE
Overlap matrix issues

### ISSUE THREAD

**Issue by driesvr** [MobleyLab/alchemical-analysis#101]
Hi everyone, I'm having some trouble with the overlap matrix of my simulations. I have several highly populated columns and several completely empty ones. I uploaded a copy of all outputs, along with a sample mdp input file [here](https://www.dropbox.com/sh/sgibpyviedu23gk/AABfIAsT3gjNj14iTpjmBm3sa?dl=0). I'm trying to alchemically decouple a small ligand over the course of 30 lambda values. I'm initially applying the boresch set of restraints, followed by coulomb and vdw decoupling. 

Thanks in advance

Dries

**Comment by davidlmobley** [comment]
I agree that your overlap matrix looks concerning. To avoid me having to read all your .mdp files when I'm crunched for time, could you briefly summarize your protocol? Specifically, what does your lambda vector look like -- do you first restrain, then charge and vdW, or are some of these transformations overlapping? How many lambdas for each? (i.e. are there obvious reasons for the bands at lambda 4, 8, 13, etc.?).

 It seems to me like there are a couple of possibilities here:
1) Your overlap matrix really is that way
2) You're suffering from a parser issue where, when using a set of lambda values that modifies other terms in the Hamiltonian other than Coulomb and vdW, something goes wacky in how the results are displayed

I actually think (1) is more likely since, while we do have some issues in category (2), the only place I've seen these show up is in the attempt to break down free energies by component in the results file, because the components may not be identified well when you're using a more-complex set of lambda vectors.

@mrshirts - thoughts?

**Comment by driesvr** [comment]
Hi David,
No real reason for the strange bands that I could think of. My setup is as follows:
First restraining over 11 lambdas, then removing coulomb over 4 lambdas, finally removing VdW interactions over 15 lambdas. The lambda protocol is taken from Matteo Aldeghi's tutorial on alchemistry.org. 
Lambdas in more detail:
`bonded-lambdas           = 0.0 0.01 0.025 0.05 0.075 0.1 0.2 0.35 0.5 0.75 1.0 1.00 1.0 1.00 1.0 1.00 1.0 1.0 1.0 1.0 1.0 1.0 1.00 1.0 1.00 1.0 1.00 1.0 1.00 1.0
coul-lambdas             = 0.0 0.00 0.000 0.00 0.000 0.0 0.0 0.00 0.0 0.00 0.0 0.25 0.5 0.75 1.0 1.00 1.0 1.0 1.0 1.0 1.0 1.0 1.00 1.0 1.00 1.0 1.00 1.0 1.00 1.0
vdw-lambdas              = 0.0 0.00 0.000 0.00 0.000 0.0 0.0 0.00 0.0 0.00 0.0 0.00 0.0 0.00 0.0 0.05 0.1 0.2 0.3 0.4 0.5 0.6 0.65 0.7 0.75 0.8 0.85 0.9 0.95 1.0
`

**Comment by davidlmobley** [comment]
Well, then, that's very odd. Have you looked at distributions of work values (forward and reverse) at the lambda values which appear "problematic" to see whether these overlap well?

**Comment by FEPanalysis** [comment]
Dries, David,

Once you encounter a weird looking overlap matrix take a look at the relative population of the states (it is a part of the screen printout). This is what you get when running with the default settings (the key flag here is `-i` which puts a threshold on the number of uncorrelated samples to proceed with):


Number of correlated and uncorrelated samples:

 State            N          N_k        N/N_k

WARNING: Only 34 uncorrelated samples found at lambda number 0; proceeding with analysis using correlated samples...
     0        50001        50001      1489.07
     1        50001           66       762.14
     2        50001           64       788.33
     3        50001          296       169.35
     4        50001         1792        27.91
     5        50001         1387        36.06
     6        50001          720        69.52
     7        50001        14969         3.34
WARNING: Only 47 uncorrelated samples found at lambda number 8; proceeding with analysis using correlated samples...
     8        50001        50001      1086.23
     9        50001        17887         2.80
    10        50001           67       748.33
    11        50001          375       133.53
    12        50001          350       143.01
WARNING: Only 24 uncorrelated samples found at lambda number 13; proceeding with analysis using correlated samples...
    13        50001        50001      2089.23
    14        50001          115       438.23
    15        50001          168       299.35
    16        50001          688        72.69
    17        50001         1964        25.46
    18        50001           98       511.31
    19        50001         3164        15.80
    20        50001         1455        34.38
    21        50001          374       134.01
    22        50001         5595         8.94
    23        50001         2570        19.46
    24        50001          202       248.54
    25        50001          757        66.07
    26        50001         4047        12.36
    27        50001          745        67.18
    28        50001         6694         7.47
    29        50001         7027         7.12

1, 8, and 13 are the maximally populated states (and are enormous compared to the majority of the states comprised of a few hundred samples or less) that overlap with pretty much every other state, hence the prominent vertical lines at these lambdas on the matrix graph.

When that population bias is eliminated (run with `-i 60000`) the overlap matrix is back to its regular look. One may argue that you get this good-looking overlap matrix at the expense of the increased uncertainties in dG, but the `result.txt` show that the uncertainties are actually way smaller when the analysis is performed on all, i.e. correlated, samples. My recommendation is Do not bother with un-correlating at all when you have unevenly (ten- and, in some cases, almost hundred-fold difference) populated states.

**Comment by driesvr** [comment]
Hi @FEPanalysis, thanks for the advice. I'll keep that in mind!
