### ISSUE TITLE
Switch to MIT license?

### ISSUE THREAD

**Issue by davidlmobley** [MobleyLab/alchemical-analysis#105]
I'd like to switch this to the MIT license in view of the license we are using for other software in the area now. Any objections? If I don't hear in two weeks I'll assume approval. @halx , @mrshirts , @shuail , @FEPanalysis ?

**Comment by halx** [comment]
I'm fine with this.

**Comment by shuail** [comment]
Fine with me.

**Comment by mrshirts** [comment]
OK with me.

**Comment by orbeckst** [comment]
This would be great because then code can be re-used in [alchemlyb](https://github.com/alchemistry/alchemlyb)!

**Comment by davidlmobley** [comment]
@orbeckst - great. I think we'll be able to do this as I've heard from the active people already; I just need to give it a little longer.

We should talk about plans -- I know David Dotson has moved on so I was uncertain what's happening with `alchemlyb`. I'll get in touch by e-mail.

**Comment by FEPanalysis** [comment]
This is to inform David that Pavel does not object.

**Comment by davidlmobley** [comment]
Resolved by #106 . cc @orbeckst
