### ISSUE TITLE
Mbar result blank !

### ISSUE THREAD

**Issue by JavadNoroozi** [MobleyLab/alchemical-analysis#110]
I don't get any output for MBAR result, while other methods are there.

**Comment by davidlmobley** [comment]
Can you give more details, @JavadNoroozi ? Right now the text above is blank. I can see from the history that you edited it a couple of times to change what was reported here, but to troubleshoot we will need input files as well as your output.

Please also note that we are working to move most of this functionality to the more general tool `alchemlyb`, which should be more reliable at present but does not yet have some of the plotting functionality available here: https://github.com/alchemistry/alchemlyb

**Comment by JavadNoroozi** [comment]
David, 
Thank you so much, I figured that out and that was because of  a silly mistake with GROMACS command dhdl=1 and it should be dhdl=-1 for MBAR to collect the data from all neighboring states rather than only one state for MBAR, otherwise the MBAR output by alchemical.py would be a blank table. 

PS: I could not find the delete button to remove my post, that is why I left it blank

**Comment by davidlmobley** [comment]
OK, thanks. It's the "close issue" button.
