### ISSUE TITLE
Qestion of alchemical_analysis.py

### ISSUE THREAD

**Issue by okimoto1** [MobleyLab/alchemical-analysis#113]
I'm new to alchemical free energy calculation,
I tested solvation free energy calculation of a ligand using 20 lambdas, 
with reference to this site (http://www.alchemistry.org/wiki/Absolute_Binding_Free_Energy_-_Gromacs_2016).
And I could obtain the result of MBAR by using alchemical_analysis.py.

Next, for each lambda, we performed MD simulations at initial different momenta 
and would like to calculate MBAR results by using alchemical_analysis.py.
In this case, I don't know how to do (file name, etc...).

I would appreciate it very much if you could tell me the method.

**Comment by okimoto1** [comment]
supplementary information:
I prepared two different directories data0 and data1. Each directory contains dhdl.??.xvg files.
And I did the following operation:
/alchemical-analysis-master/alchemical_analysis/alchemical_analysis.py -d data0 data1 -q xvg -p dhdl -u kcal -r 6 -g -w -c -f 5
We could obtain the  mbar result but it seems to be the result of only data0.

I would appreciate your support.

**Comment by davidlmobley** [comment]
Just to be clear, you're saying you would like to analyze two free energy calculations at once? But, the two free energy calculations are just different trials for the same system?

Assuming that's the case, this is not an operation we currently support, nor do we have plans to do so. It seems like you could (a) analyze them separately and then average, or (b) concatenate your xvg files together and analyze them as a unit.

**Comment by okimoto1** [comment]
As you said, I would like to analyze tow free energy calculations for the same system.
Accoding to your addvice, I will try to do  (a) or (b).
Thank you for your advice.
