### ISSUE TITLE
TI on AMBER18 pmemd

### ISSUE THREAD

**Issue by geraili-hosein** [MobleyLab/alchemical-analysis#116]
Hi,
With AMBER18 pmemd on GPU, the MBAR data will be reported on the output file like this: 
MBAR Energy analysis:
Energy at 0.0100 =   -7177.9619
in each step that data is outputted. The error when using alchemical_analysis for me is:
ERROR: gradient samples have been found for 101 lambdas:
       but MBAR data has 1:
0.81.

What should I do to resolve that?

Best

**Comment by davidlmobley** [comment]
Sorry for the delay. You should switch to using `alchemlyb`.
