### ISSUE TITLE
GOMC parser

### ISSUE THREAD

**Issue by msoroush** [MobleyLab/alchemical-analysis#117]
Hi everyone, 

I am working on implementing free energy calculation in [GOMC](https://github.com/GOMC-WSU/GOMC/tree/FreeEnergy) and I have been working on GOMC parser for alchemical-analysis and you can find my implementation in my [GitHub](https://github.com/msoroush/alchemical-analysis). I attached my results here and you can find the raw data in `samples/gomc/met-wat-NVT`.

I have few questions and concerns about alchemical-analysis and I would appreciate if your could give me some feedback. 

1. alchemical-analysis modifies the raw data as mentioned in previous issue #95. This causes problem when I run alchemical-analysis on unfinished simulation data file.
2. Forward and backward analysis on unfinished simulation results in wrong value. I think we need to look into all files and use the minimum simulation time/steps to perform the analysis.
3. The overlap matrixes in the result directory that I attached is very strange. Summation of probability in each row is one, but not for each column. Is this behavior expected or not? When I plot my energy distribution for neighboring states, they have very good overlap as you can see in attached images. So why I am seeing no overlap (between lambda 9,10,11) in overlap matrix?
4. How do we calculate the correlated and uncorrelated samples? 

I would appreciate your help and suggestion.

[result.zip](https://github.com/MobleyLab/alchemical-analysis/files/3113138/result.zip)
![energyHist](https://user-images.githubusercontent.com/13317444/56674168-8c2eb480-6687-11e9-8301-768ad106ee64.png)
![energyplot](https://user-images.githubusercontent.com/13317444/56674169-8c2eb480-6687-11e9-8ce7-e4fbb886b217.png)
![Screen Shot 2019-04-24 at 12 04 23 PM](https://user-images.githubusercontent.com/13317444/56675023-2a6f4a00-6689-11e9-9fa0-bf335cd260e4.png)

**Comment by davidlmobley** [comment]
Hi, we're no longer supporting alchemical-analysis and are moving towards `alchemlyb` (github.com/alchemistry/alchemlyb) instead, and long-term will be migrating the plotting functionality, etc. there. `alchemlyb` already has much of the key functionality and there's general agreement that we should be porting in the remaining aspects (overlap matrix plots, etc.).

Essentially, the issues you're running into relate to those driving this change: While functional, `alchemical-analysis` is not well designed enough to be easily maintainable, and, when applying it to calculations other than those for which it was originally envisioned, one frequently runs into problems.  There's also no testing framework in place, meaning that it's very difficult to know if "fixes" might accidentally break something. In contrast, the `alchemlyb` framework is much better designed, easily maintainable, modular, etc. We also have automated testing in place (and plans to continue extending that). 

So, I'd highly encourage you to check that out and consider contributing there, and move away from `alchemlyb`.

**Comment by orbeckst** [comment]
Note that @msoroush added the GOMC parser to alchemlyb https://github.com/alchemistry/alchemlyb/issues/77 so I think this issue can be safely closed.

**Comment by davidlmobley** [comment]
Thanks!
