### ISSUE TITLE
TI analysis using AMBER18

### ISSUE THREAD

**Issue by DDGmichigan** [MobleyLab/alchemical-analysis#120]
Hi,
I am in the process of analysing the absolute binding free energy calculation of acetonitrile (small molecule) to a kinase protein.
I have generated data for 12 lambda windows (not equi spaced) for acetontrile in water (folder name is ligand_water) and I have a separate  folder (ligand_protein) having 12 lambda windows of protein+acetonitrile simulation.

I am wanting to analyse my free energy change using alchemical-analysis program.
I went to /users/debarati/MOBLEY/alchemical-analysis/samples/amber/data

There are 10 lambda folders 0.0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1.0
and each folder has ti002.out and ti003.out I could not understand what is the difference between these 2 file outputs? For my case (disappear C3N from protein) I have 12 lambda windows, and each have one output file as I am doing my decharge and vdw steps as one and not multiple steps
Can you help me setup the analysis script?
Thanks

**Comment by davidlmobley** [comment]
Please try to use `alchemlyb` rather than `alchemical-analysis` as we no longer support this program.

**Comment by davidlmobley** [comment]
https://github.com/alchemistry/alchemlyb

**Comment by DDGmichigan** [comment]
I cannot find any tutorial on how to use alchemlyb, at least alchemical-analysis has a tutorial and samples to run it.

**Comment by davidlmobley** [comment]
That's true, except that (a) we have never used it for AMBER files in my group, (b) don't have anyone using it, and (c) don't have anyone developing alchemical-analysis anymore, having moved to alchemlyb.

I suggest you take your question -- and your request for tutorials -- there and hopefully we can help you over there.

**Comment by DDGmichigan** [comment]
Hello Prof Mobley,
Thanks
I am trying to do an absolute free energy calc of a small molecule binding to a src-kinase protein,
My small molecule is acetonitrile.
I have run all the steps in pmemd.cuida (AMBER 18) and have 2 separate folders C3N in protein and C3N in water, as i need to do a disappear my C3N from the protein pocket and disappear my C3N molecule in water. now in alchemical analysis there is  a sample folder and underneath that is a AMBER folder "data". it has 10 lambda folders 0.1, 0.2, 0.3 so on till 1.0, each of the folder has 2 output files  by the name ti002.out ti003.out, can you explain why?
Thanks
Regards
Debarati
