### ISSUE TITLE
Differences between MBAR and BAR

### ISSUE THREAD

**Issue by AnguseZhang** [MobleyLab/alchemical-analysis#123]
When performing FEP, I found there are significant differences between MBAR and BAR, as the figure shows.

![image](https://user-images.githubusercontent.com/38939321/80530190-3b087d80-89cb-11ea-92fa-b575d350a60e.png)

![image](https://user-images.githubusercontent.com/38939321/80527330-c7fd0800-89c6-11ea-82ee-c8b77d619563.png)

I used example from FESetup: T4 with  benzol and oxylene.  The large gap often appears in solvated simulations. (I would also want to know the reference value of complex and solvated ddG 
for this system)

When only putting data of two adjacent states into MBAR,  MBAR results are the same with BAR.
But putting data of all states, the gap appears.

![image](https://user-images.githubusercontent.com/38939321/80527825-8de03600-89c7-11ea-8a98-3162d377391b.png)

This is my code

`
python alchemical_analysis.py -d . -q xvg -p dhdl -u kJ
`

This is original file. 

[data.zip](https://github.com/MobleyLab/alchemical-analysis/files/4548109/data.zip)

I also tried alchemlyb and using original pymbar, but the results are the same.

In my view, MBAR and BAR are both unbiased estimators, and thus the estimation (free energy difference ) should be  the same.  Could you please give me some instructions ? Thanks !

**Comment by davidlmobley** [comment]
BAR and MBAR ARE slightly different, so will yield slightly different results. Sounds like your question is best directed at the `pymbar` issue tracker though.

Marking as closed since it's not an issue with this package.
