### ISSUE TITLE
setup.py installation issue

### ISSUE THREAD

**Issue by sse29** [MobleyLab/alchemical-analysis#127]
Hello when trying to run python setup.py install, I got this error:

 numexpr/interpreter.cpp: In function ‘PyObject* NumExpr_run(NumExprObject*, PyObject*, PyObject*)’:
numexpr/interpreter.cpp:1206:17: error: ‘PyDataType_SET_ELSIZE’ was not declared in this scope; did you mean ‘PyDataType_ISUNSIZED’?
 1206 |                 PyDataType_SET_ELSIZE(dtypes[0], (npy_intp)self->memsizes[1]);
      |                 ^~~~~~~~~~~~~~~~~~~~~
      |                 PyDataType_ISUNSIZED
numexpr/interpreter.cpp:1452:29: error: ‘PyDataType_ELSIZE’ was not declared in this scope; did you mean ‘PyDataType_ISUNSIZED’?
 1452 |         self->memsizes[i] = PyDataType_ELSIZE(dtypes_tmp[i]);
      |                             ^~~~~~~~~~~~~~~~~
      |                             PyDataType_ISUNSIZED
error: Setup script exited with error: command '/usr/bin/gcc' failed with exit code 1

Can you please check?
Thank you for assistance.

Best,
Sarah

**Comment by davidlmobley** [comment]
Thanks for your interest. As per our main [readme.md](https://github.com/MobleyLab/alchemical-analysis), alchemical-analysis is no longer maintained and you should be looking at alchemlyb instead.

**Comment by sse29** [comment]
Thank you so much!
