### ISSUE TITLE
Provide a utility tool to attempt cleanup of bad GROMACS data

### ISSUE THREAD

**Issue by davidlmobley** [MobleyLab/alchemical-analysis#15]
On rare occasions, GROMACS writes get interrupted by networking issues resulting on corrupted data on one line of an otherwise complete xvg file used by alchemical analysis. Currently this results in an exception (seen below). Reworking the code to deal with this would involve major efficiency hits as far as I can tell. Probably a better solution, at least for now, is to provide a utility tool which can be run to clean up the `.xvg` files in question in problematic cases (basically by deleting corrupted lines - which typically seem to be just a single line). 

Here's an example set of data:
https://drive.google.com/file/d/0B5sFkoaaNUxtRWtYWTY3RnBUMnM/view?usp=sharing

Here's the exception:
Loading in data from ./prod.1.xvg (state 1) ...
Traceback (most recent call last):
  File "/home/pklimovi/analysis/alchemical-free-energy/alchemical_analysis.py", line 1077, in <module>
    nsnapshots, lv, dhdlt, u_klt = parsers.parser_gromacs.readDataGromacs(P)
  File "/data11/home/pklimovi/analysis/alchemical-free-energy/parsers/parser_gromacs.py", line 280, in readDataGromacs
    f.iter_loadtxt(nf)
  File "/data11/home/pklimovi/analysis/alchemical-free-energy/parsers/parser_gromacs.py", line 120, in iter_loadtxt
    data = numpy.fromiter(iter_func(), dtype=float)
ValueError: invalid literal for float(): 0.8063

If I search for that string in the file it looks like there's a bad (corrupted) line in the file on line 12520.

**Comment by davidlmobley** [comment]
I believe @limn1 will write a tool which does this then we can put it on here.

**Comment by bannanc** [comment]
@limn1 @davidlmobley 

I think I have a fix for this worked out, we needed one in a related issue. I put it on gitHub here:
https://github.com/bannanc/ManipulateXVG

**Comment by davidlmobley** [comment]
Resolved by #78 by adapting @bannanc 's code. Thanks!
