### ISSUE TITLE
mbar.getFreeEnergy differences returns an unexpected number of arguments

### ISSUE THREAD

**Issue by spelmer** [MobleyLab/alchemical-analysis#20]
Hi,

The script failed with the following messages:

[ snip... ]
Final dimensionless free energies
f_k = 
[  0.           4.55294129   8.48088947  10.41122752  11.36350297
  11.95779766  11.98970287   9.30249125   7.6417943 ]
MBAR initialization complete.
Traceback (most recent call last):
  File "/data/user/sw/alchemical-analysis/alchemical_analysis.py", line 1130, in <module>
    Deltaf_ij, dDeltaf_ij = estimatewithMBAR(u_kln, N_k, P.relative_tolerance, regular_estimate=True)
  File "/data/user/sw/alchemical-analysis/alchemical_analysis.py", line 252, in estimatewithMBAR
    (Deltaf_ij, dDeltaf_ij, theta_ij) = MBAR.getFreeEnergyDifferences(uncertainty_method='svd-ew')
ValueError: need more than 2 values to unpack

Could you please provide a solution to this? I would appreciate it. Here is the command line used to invoke the command:  
    $ python /data/user/sw/alchemical-analysis/alchemical_analysis.py -o analysis -p Ethanol.dhdl -s 0 -t 300 -v

I can provide the data I am using as well (its small, only 50 ps worth of data); if you need it, where should I put it so you can access it? Thanks for your help. Here is the header for lambda = 0:

\# This file was created Sun May 24 08:22:44 2015
\# Created by:
\# GROMACS:      mdrun_mpi_d, VERSION 5.0.5 (double precision)
\# Executable:   /usr/local/gromacs/bin/mdrun_mpi_d
\# Library dir:  /usr/local/gromacs/share/gromacs/top
\# Command line:
\#   mdrun_mpi_d -multi 9 -replex 1000 -nex 100000 -deffnm Ethanol. -dhdl Ethanol.dhdl.
\# mdrun_mpi_d is part of G R O M A C S:
\#
\# Groningen Machine for Chemical Simulation
\#
@    title "dH/d\xl\f{} and \xD\f{}H"
@    xaxis  label "Time (ps)"
@    yaxis  label "dH/d\xl\f{} and \xD\f{}H (kJ/mol [\xl\f{}]\S-1\N)"
@TYPE xy
@ subtitle "T = 300 (K) \xl\f{} state 0: (coul-lambda, vdw-lambda) = (0.0000, 0.0000)"
@ view 0.15, 0.15, 0.75, 0.85
@ legend on
@ legend box on
@ legend loctype view
@ legend 0.78, 0.8
@ legend length 2
@ s0 legend "Total Energy (kJ/mol)"
@ s1 legend "dH/d\xl\f{} coul-lambda = 0.0000"
@ s2 legend "dH/d\xl\f{} vdw-lambda = 0.0000"
@ s3 legend "\xD\f{}H \xl\f{} to (0.0000, 0.0000)"
@ s4 legend "\xD\f{}H \xl\f{} to (0.2000, 0.0000)"
@ s5 legend "\xD\f{}H \xl\f{} to (0.5000, 0.0000)"
@ s6 legend "\xD\f{}H \xl\f{} to (1.0000, 0.0000)"
@ s7 legend "\xD\f{}H \xl\f{} to (1.0000, 0.2000)"
@ s8 legend "\xD\f{}H \xl\f{} to (1.0000, 0.4000)"
@ s9 legend "\xD\f{}H \xl\f{} to (1.0000, 0.6000)"
@ s10 legend "\xD\f{}H \xl\f{} to (1.0000, 0.8000)"
@ s11 legend "\xD\f{}H \xl\f{} to (1.0000, 1.0000)"
@ s12 legend "pV (kJ/mol)"
0.0000 -28913.188 14.682067 8.8265472 0.0000000 2.9364134 7.3410336 14.682067 17.557088 21.936508 27.137445 32.781006 38.647377 1.6391496
0.2000 -28904.606 57.658838 -33.534042 0.0000000 11.531768 28.829419 57.658838 55.403482 57.872462 62.203406 67.342486 72.837012 1.6398901
0.4000 -28867.621 50.950735 -59.005125 0.0000000 10.190147 25.475367 50.950735 45.220515 46.121345 49.772451 54.682820 60.188709 1.6413282
0.6000 -28940.959 60.787208 -84.862704 0.0000000 12.157442 30.393604 60.787208 51.066626 49.699611 52.078965 56.290448 61.432133 1.6436758
0.8000 -29012.527 58.265203 -9.2633724 0.0000000 11.653041 29.132602 58.265203 58.815212 62.352019 67.351139 73.089061 79.191673 1.6479552
1.0000 -28913.114 52.140243 -56.167506 0.0000000 10.428049 26.070121 52.140243 46.579172 47.537230 51.377544 56.591160 62.473134 1.6529072
1.2000 -28995.072 54.985777 -60.363362 0.0000000 10.997155 27.492889 54.985777 48.927036 49.548740 52.984165 57.714439 63.059163 1.6569541
1.4000 -29047.081 53.638803 -28.937149 0.0000000 10.727761 26.819402 53.638803 51.889673 54.496837 58.859205 63.994079 69.471719 1.6605582
1.6000 -28980.959 48.438421 -49.952803 0.0000000 9.6876842 24.219211 48.438421 43.895239 45.418109 49.523529 54.831600 60.713221 1.6658269
1.8000 -29088.399 70.849208 -28.480365 0.0000000 14.169842 35.424604 70.849208 68.868205 71.363564 75.972778 81.635058 87.822310 1.6709045
2.0000 -29081.420 43.606014 -16.728997 0.0000000 8.7212029 21.803007 43.606014 43.122092 46.265671 51.235331 57.151142 63.548873 1.6758257
2.2000 -29100.045 62.089164 -16.022554 0.0000000 12.417833 31.044582 62.089164 62.068713 65.700084 70.937465 76.925393 83.257956 1.6783177
2.4000 -29091.456 69.023006 -59.653885 0.0000000 13.804601 34.511503 69.023006 63.206763 64.268652 68.302500 73.737728 79.850794 1.6788066
2.6000 -29137.602 79.838816 -55.844545 0.0000000 15.967763 39.919408 79.838816 74.157667 74.974791 78.801615 84.119636 90.190026 1.6785062
2.8000 -29137.617 114.95491 -76.349850 0.0000000 22.990981 57.477453 114.95491 106.58465 106.26599 109.59500 114.70361 120.70368 1.6781231

Sid

**Comment by FEPanalysis** [comment]
@davidlmobley This should be addressed to whoever put 'theta_ij' in line 252:
(Deltaf_ij, dDeltaf_ij, theta_ij) = MBAR.getFreeEnergyDifferences(uncertainty_method='svd-ew')

**Comment by davidlmobley** [comment]
@spelmer - can you confirm that you are using the latest pymbar? It looks to me like the pymbar API for this function was changed sometime probably around early January (still tracking down the exact commit) to return three variables rather than two. Your alchemical-analysis is complaining that pymbar is giving back only two things.

@FEPanalysis - this apparently came in before we moved from pymbar so you or Kyle reviewed it. But it seems correct, unless I'm missing something.

**Comment by davidlmobley** [comment]
@spelmer , @FEPanalysis - no, I take it back - this IS incorrect as it only should return three arguments if getFreeEnergyDifferences has return_theta = True. 

I would go back to see how this got in here, but it's complicated by the fact that we recently moved from pymbar to a separate repository, confusing the history. So I'll just fix it.

**Comment by wesbarnett** [comment]
Hey @davidlmobley (in response to query from #19) I haven't come across this issue. I keep up pretty regularly with syncing my pymbar and alchemical_analysis script with what's on Github, so maybe there's something a play there.

**Comment by davidlmobley** [comment]
Hmm. Apparently this is an issue which depends on whether one is running pymbar 2.1.0b0 (available via conda) or 3.0.0.dev0 (the current github main branch), though it's unclear to me *why* as yet since both APIs specify that theta is not returned unless return_theta is set to True.

**Comment by davidlmobley** [comment]
OK, I figured this out and it's a "bug"/undocumented API change in `pymbar` so that even though the doc string is the same in the 2.1.0b0 release (from conda) and the main branch, the actual function behavior is different. 

Apparently the doc string is in error for 3.0.0 so that the `mbar.getFreeEnergyDifferences` function always returns three arguments whether they are asked for or not. 

I've started an issue for this on `pymbar` (https://github.com/choderalab/pymbar/issues/187) but in the meantime will fix it here by explicitly asking for the third argument to be returned so that both versions will work.

**Comment by davidlmobley** [comment]
Fixed now.

**Comment by spelmer** [comment]
Sorry I wasn't able to respond until now. I just checked and MBAR is now working. Thanks for your help.

**Comment by jchodera** [comment]
I'd love to see this restored back to its original behavior of returning only two arguments by default.

**Comment by davidlmobley** [comment]
@jchodera - I'm confused. Are you asking about the `pymbar` API? 

This issue you're commenting on here relates to how I had to change `alchemical-analysis` to accommodate API changes in `pymbar`. It sounds like you are asking for `pymbar` to have its API changed to only return two arguments by default, but if I remember correctly, it DOES already return only two arguments by default. And, either way, it's the `pymbar` repository where `pymbar` API issues should be addressed. `alchemical-analysis` simply uses the `pymbar` API, and I didn't make any changes to it one way or the other.
