### ISSUE TITLE
-a amber -m all throws error

### ISSUE THREAD

**Issue by foxth** [MobleyLab/alchemical-analysis#26]
Hi David,

I tried alchemical_analysis.py with the amber test files provided in samples/amber/data

with 
python2.7 ../../../alchemical_analysis.py -a amber -p "ti*/ti" -q out -o ~/test

the script runs through and produces the expected output for TI and TI-CUBIC.

if I add the option -m all to the above call, I get the following traceback:

Traceback (most recent call last):
  File "../../../alchemical_analysis/alchemical_analysis.py", line 1184, in <module> main()
  File "../../../alchemical_analysis/alchemical_analysis.py", line 1160, in main
    Deltaf_ij, dDeltaf_ij = estimatewithMBAR(u_kln, N_k, P.relative_tolerance, regular_estimate=True)
NameError: global name 'u_kln' is not defined

Is this a bug or did I do something wrong? Any help appreciated.

Thanks,
Th.

**Comment by FEPanalysis** [comment]
TI and TI-CUBIC are the only methods for Amber as it does not output the energy differences between adjacent states ∆U_{i, i+1} needed for the FEP methods. So, yes, to some degree it is a bug because the exception catch is missing, but you are not supposed to call '-m all' with Amber.

**Comment by foxth** [comment]
Hm...maybe Im missing an important point - but in the amber mdout files there are sections starting with "MBAR Energy analysis" which print out what I always thought were the energies of the current configuration at different lamda values - and from this one could calculate the DeltaU{i,i+1} one would need...and indeed I could use the very same mdout files to generate input files for the pymbar routines to get the relative free energies via BAR or MBAR.

**Comment by FEPanalysis** [comment]
Yes, you are right, my bad.
When I played with the output files I was focusing on the "Summary of dvdl values" time series.
Because I didn't find similar time series for the DeltaU{i,i+1} energies, I concluded there wasn't any.
This will be fixed.

**Comment by foxth** [comment]
Perfect!

Thanks a lot,
Th.

Am 31.07.2015 um 21:15 schrieb FEPanalysis:

**Comment by FEPanalysis** [comment]
@davidlmobley Shall we merge Hannes' PR?

**Comment by davidlmobley** [comment]
I just had an e-mail from him the other day I need to follow up on. Hannes
- you still have a little more you want to get in here it sounded like?

Thanks.

On Tue, Dec 1, 2015 at 5:28 PM, FEPanalysis <notifications@github.com>
wrote:

> @davidlmobley <https://github.com/davidlmobley> Shall we merge Hannes' PR?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MobleyLab/alchemical-analysis/issues/26#issuecomment-161150286>
> .
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436

**Comment by davidlmobley** [comment]
But with respect to this issue - is this issue fixed now or is it still to be dealt with in one of your (Hannes' or Pavel) PRs?

**Comment by halx** [comment]
Sorry, just found this now.  Is there a way to get automatic updates on issue reports?

I think the MBAR code in the AMBER parser now works fine although I fixed a bug just today, so after the merger.  The bug however did only trigger an error in the parser when there was _no_ MBAR data in the output file.  MBAR data processing should be fine.

**Comment by davidlmobley** [comment]
OK, so @halx and @foxth - I believe this issue is resolved and will mark it closed. @foxth , please reopen if you have further issues.

@halx - to get automatic updates on issue reports, one way is to just "star" the repository in which case you should get e-mail notifications of everything. There may be more fine-grained controls as well.
