### ISSUE TITLE
Change README.md to properly point

### ISSUE THREAD

**Issue by mrshirts** [MobleyLab/alchemical-analysis#30]
Currently the README.md refers to:

gromacs/README.md, sire/README.md, and amber/README.md

But these folders don't exist.  I think it should be 

samples/gromacs/README.md

etc.

**Comment by mrshirts** [comment]
Also the readme's appear to have the old directory names there as well.

**Comment by davidlmobley** [comment]
Yes, that's correct - needs updating. Do a PR? (Or I can do sometime soon,
but something came up so I'm out today).

On Tue, Aug 11, 2015 at 8:34 PM, Michael Shirts <notifications@github.com>
wrote:

> Also the readme's appear to have the old directory names there as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MobleyLab/alchemical-analysis/issues/30#issuecomment-130149075>
> .
>



-- 
David Mobley
Associate Professor
Department of Pharmaceutical Sciences
Department of Chemistry
3134B Natural Sciences I
University of California, Irvine
Irvine, CA 92697
dmobley@uci.edu
work (949) 824-6383
cell (949) 385-2436

**Comment by davidlmobley** [comment]
Fixed by #55
