### ISSUE TITLE
multiple expanded ensemble files not working

### ISSUE THREAD

**Issue by mrshirts** [MobleyLab/alchemical-analysis#36]
One feature the code use to have was the ability to load together multiple expanded ensemble files.  For example, there might be 18 states, but 4 separate expanded ensemble replicas. Previously (several generations ago) the code could load in all 4 of those files, and put all the corresponding samples together into a single u_kln matrix.  However, after the edits, this can't be done.  

One issue that's relatively easily corrected is for expanded ensemble reading the number of states from the file, rather than counting the number of files (which may not be the same). I've posted a pull_request with this change. However, it still is making some assumptions about how the data is loaded in to the dhdl array and u_kln matrix, and I don't know that I can updated those without messing up the data processing changes. 

Any thoughts for how this functionality could be readded?

**Comment by mrshirts** [comment]
Note: I can provide sample files for debugging as needed.

**Comment by davidlmobley** [comment]
I'll give @FEPanalysis a bit to answer this since I haven't worked with the processing code since he optimized it. However, I'm sure some sample files would be helpful.

**Comment by FEPanalysis** [comment]
We definitely have to put the EE files into the "samples" folder and prepare a test.
There are more problems with the EE.
The first one it does not work, even for a regular single file case, the problem being the line 128 of parser_gromacs.py which used to be "r1, r2 = (read_dhdl_end, read_dhdl_end+K)".
The second problem is that it does not display the TI uncertainties properly -- those for Coulomb appear to be zero.
I will be looking at this more.

**Comment by davidlmobley** [comment]
@mrshirts - please provide sample files.

**Comment by FEPanalysis** [comment]
I am very close to be done with this.
Will submit PR this week.
Thanks for waiting.

**Comment by davidlmobley** [comment]
@mrshirts - should be fixed by #43 ; can you check?

**Comment by davidlmobley** [comment]
Marking as closed, @mrshirts . Please reawaken if you still have problems here.
