### ISSUE TITLE
NameError: global name 'parametersB' is not defined

### ISSUE THREAD

**Issue by camizanette** [MobleyLab/alchemical-analysis#37]
I was using a different format of topologies files and I got this error saying the variable parametersB is not defined previously. The issue comes from Part IV, when it is processing the dihedrals and the top file format doesn't match with what the code is expecting, going to an exception in line 380. What I have noticed is acpype and parmed return different dihedrals functions types (9 and 1), and amb2gmx.pl returns the function type 3 (the one that works). I can provide samples in case it is necessary.

Traceback (most recent call last):
  File "../../local/alchemical-setup-master/alchemical-setup.py", line 549, in <module>
    buildBonded()                                                # Part  IV.
  File "../../local/alchemical-setup-master/alchemical-setup.py", line 429, in buildBonded
    postprocessDihedrals()
  File "../../local/alchemical-setup-master/alchemical-setup.py", line 385, in postprocessDihedrals
    if l['parameters'][-1] != parametersB[-1]:
NameError: global name 'parametersB' is not defined

**Comment by davidlmobley** [comment]
Yes, please provide a link to input files to reproduce the problem.

Thanks.


On Mon, Nov 2, 2015 at 10:04 PM, camizanette <notifications@github.com>
wrote:

> I was using a different format of topologies files and I got this error
> saying the variable parametersB is not defined previously. The issue comes
> from Part IV, when it is processing the dihedrals and the top file format
> doesn't match with what the code is expecting, going to an exception in
> line 380. What I have noticed is acpype and parmed return different
> dihedrals functions types (9 and 1), and amb2gmx.pl returns the function
> type 3 (the one that works). I can provide samples in case it is necessary.
>
> Traceback (most recent call last):
> File "../../local/alchemical-setup-master/alchemical-setup.py", line 549,
> in
> buildBonded() # Part IV.
> File "../../local/alchemical-setup-master/alchemical-setup.py", line 429,
> in buildBonded
> postprocessDihedrals()
> File "../../local/alchemical-setup-master/alchemical-setup.py", line 385,
> in postprocessDihedrals
> if l['parameters'][-1] != parametersB[-1]:
> NameError: global name 'parametersB' is not defined
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MobleyLab/alchemical-analysis/issues/37>.
>



-- 
David Mobley
Associate Professor
Department of Pharmaceutical Sciences
Department of Chemistry
3134B Natural Sciences I
University of California, Irvine
Irvine, CA 92697
dmobley@uci.edu
work (949) 824-6383
cell (949) 385-2436

**Comment by camizanette** [comment]
Here is the dropbox link https://drive.google.com/folderview?id=0B5Hiv4aw8v8CWWU3N2ZVb2FsbWs&usp=sharing

There are two folders, one with topologies from Parmed and other from amb2gmx.pl.

Let me know if it does not work.

Thanks!

**Comment by davidlmobley** [comment]
Oops, this is an issue for alchemical-setup, yes?

Thanks.


On Tue, Nov 3, 2015 at 4:18 PM, camizanette <notifications@github.com>
wrote:

> Here is the dropbox link
> https://drive.google.com/folderview?id=0B5Hiv4aw8v8CWWU3N2ZVb2FsbWs&usp=sharing
>
> There are two folders, one with topologies from Parmed and other from
> amb2gmx.pl.
>
> Let me know if it does not work.
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MobleyLab/alchemical-analysis/issues/37#issuecomment-153531580>
> .
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436

**Comment by camizanette** [comment]
Ops. I just posted on the right place.
