### ISSUE TITLE
Coulomb Free Energy

### ISSUE THREAD

**Issue by bannanc** [MobleyLab/alchemical-analysis#42]
The Coulomb part of the free energy calculation is being reported as zero for hydration and solvation free energy calculations when we wouldn't expect it to be. This doesn't seem to be happening with the sample files that are provided. I can provide a sample set of .xvg files if needed.

**Comment by davidlmobley** [comment]
Can you provide a sample .mdp and set of .xvg's? It will have to do with
the lambda vector you are using, so we need to be able to look at this.

Thanks.

On Mon, Nov 23, 2015 at 1:26 PM, Caitlin Bannan <notifications@github.com>
wrote:

> The Coulomb part of the free energy calculation is being reported as zero
> for hydration and solvation free energy calculations when we wouldn't
> expect it to be. This doesn't seem to be happening with the sample files
> that are provided. I can provide a sample set of .xvg files if needed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MobleyLab/alchemical-analysis/issues/42>.
>



-- 
David Mobley
Associate Professor
Department of Pharmaceutical Sciences
Department of Chemistry
3134B Natural Sciences I
University of California, Irvine
Irvine, CA 92697
dmobley@uci.edu
work (949) 824-6383
cell (949) 385-2436

**Comment by bannanc** [comment]
Yes, I'll move some to dropbox and post a link momentarily

**Comment by bannanc** [comment]
Here you go: https://www.dropbox.com/sh/1vnyy2k5l13kai0/AAD4qJS971S4El5jSQUSbFCra?dl=0

The system was a solvation free energy calculation for methanol in cyclohexane. It has a set of xvg files prod.0 to prod.19 and an example mdp file prod.0.mdp. I also ran the most recent version of alchemical_analysis (downloaded this morning to check versions) so the results files are there. 

Let me know if you need anything else.

**Comment by FEPanalysis** [comment]
Wait for the expanded ensemble PR.
I'll include the fix there.
This is what you (I, that is) get with the bug fixed:

  Coulomb:        0.073  +-  0.002      0.073  +-  0.002      0.073  +-  0.002      0.072  +-  0.002      0.073  +-  0.002      0.071  +-  0.002 
  vdWaals:        3.655  +-  0.062      3.660  +-  0.062      3.711  +-  0.093      3.667  +-  0.056      3.647  +-  0.043      3.642  +-  0.052 
    TOTAL:        3.727  +-  0.062      3.733  +-  0.062      3.784  +-  0.093      3.740  +-  0.056      3.719  +-  0.043      3.713  +-  0.052

**Comment by FEPanalysis** [comment]
@bannanc by the way,
are the 'Coulomb' numbers reasonable now, or they are still too small?

**Comment by davidlmobley** [comment]
@bannanc - we think this is fixed now (by #43 which we just merged). Can you confirm? Thanks.

(Reopen if not fixed).

**Comment by bannanc** [comment]
Yes, as far as I can tell it is fixed. Thank you!
