### ISSUE TITLE
Add at least some form of a version tag to be printed to stdout and results.txt

### ISSUE THREAD

**Issue by halx** [MobleyLab/alchemical-analysis#46]
The tool needs to write out clear information about the current version.  This could be done in the same fashion as the command line that is to stdout and results.txt.

**Comment by davidlmobley** [comment]
Agreed. We also need to add clear versioning, see #13 . I don't have any experience with the automated versioning stuff so I need to investigate that, or I'm open to suggestions.

**Comment by halx** [comment]
I'm not sure how you would do automatic versioning for something as
arbitrary as a version label.  I understand this branch to be a release
branch which is updated whenever you feel like it.  If you had a "live"
branch i.e. a development branch you could just use the GIT hash.  I guess
you could update a file every time a check-out (pull) occurs.

For the time being you could just manually add a version tag e.g. by using
arparse's version action.

**Comment by halx** [comment]
'refactor' branch provides simple version information.
