### ISSUE TITLE
Allow parser-specific command-line options which get passed to parser to handle internally

### ISSUE THREAD

**Issue by halx** [MobleyLab/alchemical-analysis#47]
It should be possible for the user to set parser specific options, e.g. from the command line like -a AMBER:write_grads:verbose=3:do_something_else.  The main code will split this in a list and pass it on to the parser code.

**Comment by davidlmobley** [comment]
Can you be more specific about what problem(s) you see this solving and what you think should be implemented? I'm not necessarily opposed - I'm just not totally clear as to what you're getting at.

**Comment by halx** [comment]
This is as simple as

tmp = software.split(':')
software = tmp[0]
parser_opts = tmp[1:]

and pass parser_opts to the parser.  The parser makes use of this at it
seems fit.

MD codes have different output and features and it is useful to extract
some of those and handle them with the parser.  E.g. AMBER collects
averages of the components.  This is not vital to the code but can be
informative.  So an option could be there to write output (also to a file)
whent the user wants it.  Another option would be to write out all the
parsed gradients into a new file.  GROMACS has a nice format (XVG) but not
so in AMBER and possibly other codes.  Some codes may write out, say,
gradients very frequently e.g. every step which can be a problem with
memory so a skip options (or whatever) can come quite in handy.

Of course, these examples may be useful for all the parsers and could be
implemented as a global options list.  BTW, I think it would be useful too
to write out (again as an option) the uncorrelated gradient data.  While
the plots as done in the code now are nice a user would have full
flexibility to handle these data in whatever fashion they wish.

**Comment by davidlmobley** [comment]
OK, with this clarification I agree this is a good idea. It should be coupled to the standardization of the parser interface we've been talking about elsewhere (i.e. under #48 ).

**Comment by davidlmobley** [comment]
Also, I want to remark that we want to make sure to do this in a way that the options are just passed to the parser directly to handle internally, so that the code outside doesn't need to know about them.

**Comment by halx** [comment]
Done, although some functionality may be useful globally.

**Comment by davidlmobley** [comment]
Er, where was this done? Sorry, I'm just confused.

**Comment by halx** [comment]
In the refactor branch.  I am currently not introducing any changes to my
fork and certainly not to the master branch.

**Comment by davidlmobley** [comment]
OK, right. Do you mind submitting a PR from your "refactor" branch to the master branch here (but obviously not merging) to make it easier to:
a) see what you're doing, and
b) allow issues that are closed by those revisions to reference the PR

Usually we do this (elsewhere) by submitting a PR with the characters "[WIP]" as the first characters in the title. That stands for "work in progress" and basically means it's just there to show people what you're doing and NOT yet ready for merging. It provides a good opportunity for discussion and comments on your changes, etc. For example, see https://github.com/choderalab/openmoltools/pull/164.

In case it's not obvious - changes you push to your branch after submitting the PR will automatically go into updates to the PR, so you basically just leave it open and keep making updates until you think it's ready to merge, then you edit the title to remove the "[WIP]" from it.

**Comment by halx** [comment]
Done.

**Comment by davidlmobley** [comment]
Thanks, I got the notification and will start looking at code hopefully
soon (still way backlogged on this end).

DM


On Thu, Jan 21, 2016 at 1:09 AM, Hannes Loeffler <notifications@github.com>
wrote:

> Done.
>
> On 20 January 2016 at 19:59, David L. Mobley <notifications@github.com>
> wrote:
>
> > OK, right. Do you mind submitting a PR from your "refactor" branch to the
> > master branch here (but obviously not merging) to make it easier to:
> > a) see what you're doing, and
> > b) allow issues that are closed by those revisions to reference the PR
> >
> > Usually we do this (elsewhere) by submitting a PR with the characters
> > "[WIP]" as the first characters in the title. That stands for "work in
> > progress" and basically means it's just there to show people what you're
> > doing and NOT yet ready for merging. It provides a good opportunity for
> > discussion and comments on your changes, etc. For example, see
> > choderalab/openmoltools#164
> > <https://github.com/choderalab/openmoltools/pull/164>.
> >
> > In case it's not obvious - changes you push to your branch after
> > submitting the PR will automatically go into updates to the PR, so you
> > basically just leave it open and keep making updates until you think it's
> > ready to merge, then you edit the title to remove the "[WIP]" from it.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/MobleyLab/alchemical-analysis/issues/47#issuecomment-173343066
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MobleyLab/alchemical-analysis/issues/47#issuecomment-173507118>
> .
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436
