### ISSUE TITLE
error with -c -m ti+ti-cubic

### ISSUE THREAD

**Issue by halx** [MobleyLab/alchemical-analysis#51]
The traceback below suggest to me that the code doesn't properly guard against this combination of command line switches.  Obviously it doesn't make sense to do the CFM analysis when there is not BAR type data.

Traceback (most recent call last):
  File "/home/hhl/projects/alchemical-analysis/alchemical_analysis/alchemical_analysis.py", line 1224, in <module>
    main()
  File "/home/hhl/projects/alchemical-analysis/alchemical_analysis/alchemical_analysis.py", line 1219, in main
    plotCFM(u_kln, N_k, 50)
  File "/home/hhl/projects/alchemical-analysis/alchemical_analysis/alchemical_analysis.py", line 1111, in plotCFM
    plotdg_vs_dU(yy, df_allk, ddf_allk)
  File "/home/hhl/projects/alchemical-analysis/alchemical_analysis/alchemical_analysis.py", line 1046, in plotdg_vs_dU
    ax.fill_between(xx_i, df_allk[i]['BAR'] - ddf_allk[i]['BAR'], df_allk[i]['BAR'] + ddf_allk[i]['BAR'], color='#D2B9D3', zorder=-1)
KeyError: 'BAR'

**Comment by davidlmobley** [comment]
Indeed. Hopefully we can get this in the process of updating the argument parser. (I'm on board with your suggestions in the other issues you raised; it's just taking me some time to dig out from under a backlog of urgent stuff on this end, and @FEPanalysis must be tied up...?).

Thanks.

**Comment by halx** [comment]
Many thanks.

Optparse is obsolete but still supprorted (at least in Python 2.7) so this
is certainly not a priority thing but rather one of long term maintainance.

BTW, do you need any help?  The holiday season means that I won't have much
time but hopefully in the new year.

**Comment by davidlmobley** [comment]
Any help you want to provide will be much appreciated, i.e. if you want to
turn your issues (especially those where I've commented and agreed - and
I'll try to do more of that soon) into PRs it'll help a lot.

I don't have anyone in the group currently developing this, meaning that a
lot of the work may fall to me (and hence will be slow), though to a
limited extent I can maybe rope in Nathan Lim (who wrote the Desmond parser
recently - but he's got way too much on his plate at present). Pavel
(FEPAnalysis) has moved on to another job, so while he'll help from time to
time I imagine that's going to diminish over time. There are a couple other
people (Wes Barnett at Tulane, for example) who have contributed
substantially to the code, but it's not their job.

In hindsight (I still have a lot to learn about group management) I
probably should have been more involved with review of the code and overall
architecture, as there are a number of things here which are problematic
(like the use of global variables) and done a better job making sure there
was a smooth handoff from Pavel to someone else in the group. That said,
I'm encouraged that a number of people are starting to use it and that
makes me cautiously more optimistic about the future.

Thanks.


On Fri, Dec 18, 2015 at 10:35 AM, Hannes Loeffler <notifications@github.com>
wrote:

> Many thanks.
>
> Optparse is obsolete but still supprorted (at least in Python 2.7) so this
> is certainly not a priority thing but rather one of long term maintainance.
>
> BTW, do you need any help? The holiday season means that I won't have much
> time but hopefully in the new year.
>
>
> On 18 December 2015 at 18:21, David L. Mobley <notifications@github.com>
> wrote:
>
> > Indeed. Hopefully we can get this in the process of updating the argument
> > parser. (I'm on board with your suggestions in the other issues you
> raised;
> > it's just taking me some time to dig out from under a backlog of urgent
> > stuff on this end, and @FEPanalysis <https://github.com/FEPanalysis>
> must
> > be tied up...?).
> >
> > Thanks.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/MobleyLab/alchemical-analysis/issues/51#issuecomment-165862905
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MobleyLab/alchemical-analysis/issues/51#issuecomment-165865205>
> .
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436

**Comment by halx** [comment]
Issue fixed in 'refactor' branch.
