### ISSUE TITLE
gromacs parser

### ISSUE THREAD

**Issue by sanasaeed** [MobleyLab/alchemical-analysis#58]
i am a beginner, can you guide me about this error, how should i fix it.

Traceback (most recent call last):
  File "alchemical_analysis.py", line 1076, in <module>
    import parsers.parser_gromacs
ImportError: No module named parsers.parser_gromacs

**Comment by davidlmobley** [comment]
@sanasaeed : What platform was this on, and how did you install? Did you run the "python setup.py install", and what are the contents of your PYTHONPATH environment variable? It looks like you might just be trying to run alchemical_analysis.py without actually installing.

**Comment by sanasaeed** [comment]
dear Sir David L.Mobleyyes i installed setup.py (pymbar). this is my pythonpath:    /share/RDKit:/share/anaconda/bin
 

    On Friday, January 1, 2016 6:21 AM, David L. Mobley <notifications@github.com> wrote:
 

 @sanasaeed : What platform was this on, and how did you install? Did you run the "python setup.py install", and what are the contents of your PYTHONPATH environment variable? It looks like you might just be trying to run alchemical_analysis.py without actually installing.—

**Comment by davidlmobley** [comment]
Wait,  you installed pymbar? Or alchemical analysis AND pymbar? (These are
two different packages).

Also, the text you've quoted looks peculiar, in that there are missing
periods. Can you confirm that the below is exactly the error message you
get?

> Traceback (most recent call last):

> File "alchemical_analysispy", line 1076, in
> import parsersparser_gromacs
> ImportError: No module named parsersparser_gromacs
And, again, what platform is this on?

This has worked fine (and currently works fine!) for many of us under Linux
and OS X, so something is peculiar on your end and it's not immediately
obvious to me what it could be. I'm suspecting either an issue with what or
how you've installed, or with your environment (paths, etc). It doesn't
seem to be a problem with the package itself, unless it's a problem with
your platform (i.e. if you're in Windows, it's possible we may need to find
a Windows computer to test on...).

Thanks.

On Sun, Jan 3, 2016 at 4:01 PM, Sana Saeed <notifications@github.com> wrote:

> dear Sir David L.Mobleyyes i installed setup.py (pymbar). this is my
> pythonpath:    /share/RDKit:/share/anaconda/bin
>
>
> On Friday, January 1, 2016 6:21 AM, David L. Mobley <
> notifications@github.com> wrote:
>
>
> @sanasaeed : What platform was this on, and how did you install? Did you
> run the "python setup.py install", and what are the contents of your
> PYTHONPATH environment variable? It looks like you might just be trying to
> run alchemical_analysis.py without actually installing.—
>
> Reply to this email directly or view it on GitHub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MobleyLab/alchemical-analysis/issues/58#issuecomment-168556564>
> .
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436

**Comment by sanasaeed** [comment]
oh sorry i just installed pymbar. and i am using alchemical-analysis.py without installing.  

    On Monday, January 4, 2016 9:23 AM, David L. Mobley <notifications@github.com> wrote:
 

 Wait, you installed pymbar? Or alchemical analysis AND pymbar? (These are
two different packages).

Also, the text you've quoted looks peculiar, in that there are missing
periods. Can you confirm that the below is exactly the error message you
get?

> Traceback (most recent call last):

> File "alchemical_analysispy", line 1076, in
> import parsersparser_gromacs
> ImportError: No module named parsersparser_gromacs
And, again, what platform is this on?

This has worked fine (and currently works fine!) for many of us under Linux
and OS X, so something is peculiar on your end and it's not immediately
obvious to me what it could be. I'm suspecting either an issue with what or
how you've installed, or with your environment (paths, etc). It doesn't
seem to be a problem with the package itself, unless it's a problem with
your platform (i.e. if you're in Windows, it's possible we may need to find
a Windows computer to test on...).

Thanks.

On Sun, Jan 3, 2016 at 4:01 PM, Sana Saeed <notifications@github.com> wrote:

> dear Sir David L.Mobleyyes i installed setup.py (pymbar). this is my
> pythonpath: /share/RDKit:/share/anaconda/bin
>
>
> On Friday, January 1, 2016 6:21 AM, David L. Mobley <
> notifications@github.com> wrote:
>
>
> @sanasaeed : What platform was this on, and how did you install? Did you
> run the "python setup.py install", and what are the contents of your
> PYTHONPATH environment variable? It looks like you might just be trying to
> run alchemical_analysis.py without actually installing.—
>
> Reply to this email directly or view it on GitHub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MobleyLab/alchemical-analysis/issues/58#issuecomment-168556564>
> .
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436

**Comment by sanasaeed** [comment]
Thank you 
i installed alchemical_analysis and it worked perfectly

Regards
