### ISSUE TITLE
Make conda installable

### ISSUE THREAD

**Issue by davidlmobley** [MobleyLab/alchemical-analysis#6]

**Comment by tsenapathi** [comment]
Hi Dr. @davidlmobley I have made a conda package. have a look at https://anaconda.org/tsenapathi/alchemical-analysis.
This is currently working with Python 2 only.

**Comment by davidlmobley** [comment]
Thanks. I'll actually close the issue; we're shifting to using and contributing `alchemlyb` instead and most useful functionality from this package (which is unmaintainable) will be moved there.
