### ISSUE TITLE
order of methods

### ISSUE THREAD

**Issue by halx** [MobleyLab/alchemical-analysis#63]
I have just noticed that the order of methods is
..., 'DEXP', 'IEXP', 'GINS', 'GDEL', ...

I guess the D stands for DEL and I for INS.  So the order is exactly the opposite between the EXP formula and the Gaussian approximation.  Is this on purpose?

I also wonder what INSert and DELete stand for?  Does this terminology follow from absolute transformations?  In relative ones you can have both.

**Comment by davidlmobley** [comment]
Hi,

On Tue, Jan 5, 2016 at 6:57 AM, Hannes Loeffler <notifications@github.com>
wrote:

> I have just noticed that the order of methods is
> ..., 'DEXP', 'IEXP', 'GINS', 'GDEL', ...
>
> I guess the D stands for DEL and I for INS. So the order is exactly the
> opposite between the EXP formula and the Gaussian approximation. Is this on
> purpose?
>

Not really. It's probably that way for historical reasons (i.e. this is
probably the order Michael Shirts used in his relevant paper).

> I also wonder what INSert and DELete stand for? Does this terminology
> follow from absolute transformations? In relative ones you can have both.
>

Sort of. If the calculation being analyzed is an absolute calculation
involving turning off interactions as lambda increases, then my
recollection is that insertion would be the same direction as Widom
insertion and deletion would be the same direction as "Widom deletion"
(which is not done). Does that help?


> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MobleyLab/alchemical-analysis/issues/63>.
>



-- 
David Mobley
Associate Professor
Department of Pharmaceutical Sciences
Department of Chemistry
3134B Natural Sciences I
University of California, Irvine
Irvine, CA 92697
dmobley@uci.edu
work (949) 824-6383
cell (949) 385-2436

**Comment by halx** [comment]
Many thanks for the explanation.  I guess the order should then stay as it is.
