### ISSUE TITLE
Consider implementing extrapolation scheme for MBAR to handle AMBER's lack of endpoint data

### ISSUE THREAD

**Issue by halx** [MobleyLab/alchemical-analysis#66]
I wonder if it would make sense to introduce an extrapolation scheme for "incomplete" MBAR data data.  The principal problem for me is sander which cannot sample the end-points.  I also heard from some other person that he doesn't sample the end-points and relies on extrapolation apparently.  Is there any good reason why that should not be done?  I certainly understand that this shouldn't be used to bridge larger gaps.

**Comment by davidlmobley** [comment]
I'm OK with doing this (though I think it's ridiculous that AMBER still
can't sample endpoints) though there should be something sensible
implemented to keep people from doing extrapolations which are too big.
Ideas for how to determine what "too big" is?

Thanks.

On Wed, Jan 13, 2016 at 7:33 AM, Hannes Loeffler <notifications@github.com>
wrote:

> I wonder if it would make sense to introduce an extrapolation scheme for
> "incomplete" MBAR data data. The principal problem for me is sander which
> cannot sample the end-points. I also heard from some other person that he
> doesn't sample the end-points and relies on extrapolation apparently. Is
> there any good reason why that should not be done? I certainly understand
> that this shouldn't be used to bridge larger gaps.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MobleyLab/alchemical-analysis/issues/66>.
>



-- 
David Mobley
Associate Professor
Department of Pharmaceutical Sciences
Department of Chemistry
3134B Natural Sciences I
University of California, Irvine
Irvine, CA 92697
dmobley@uci.edu
work (949) 824-6383
cell (949) 385-2436

**Comment by davidlmobley** [comment]
Curvature is a big factor for accuracy of TI, but I don't believe it is for
BAR/MBAR, where it is overlap. Unless you have a more generalized concept
of curvature that does apply to BAR/MBAR?

On Wed, Jan 13, 2016 at 11:48 AM, Hannes Loeffler <notifications@github.com>
wrote:

> Form linear transformations I have seen that the MBAR energies for a given
> lambda is linear, to non-linear softcore transformation obviously not.
> Maybe some analysis of curvature? The TI code could also benefit from this.
>
> On 13 January 2016 at 16:25, David L. Mobley <notifications@github.com>
> wrote:
>
> > I'm OK with doing this (though I think it's ridiculous that AMBER still
> > can't sample endpoints) though there should be something sensible
> > implemented to keep people from doing extrapolations which are too big.
> > Ideas for how to determine what "too big" is?
> >
> > Thanks.
> >
> > On Wed, Jan 13, 2016 at 7:33 AM, Hannes Loeffler <
> notifications@github.com
> > >
> > wrote:
> >
> > > I wonder if it would make sense to introduce an extrapolation scheme
> for
> > > "incomplete" MBAR data data. The principal problem for me is sander
> which
> > > cannot sample the end-points. I also heard from some other person that
> he
> > > doesn't sample the end-points and relies on extrapolation apparently.
> Is
> > > there any good reason why that should not be done? I certainly
> understand
> > > that this shouldn't be used to bridge larger gaps.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/MobleyLab/alchemical-analysis/issues/66>.
> > >
> >
> >
> >
> > --
> > David Mobley
> > Associate Professor
> > Department of Pharmaceutical Sciences
> > Department of Chemistry
> > 3134B Natural Sciences I
> > University of California, Irvine
> > Irvine, CA 92697
> > dmobley@uci.edu
> > work (949) 824-6383
> > cell (949) 385-2436
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/MobleyLab/alchemical-analysis/issues/66#issuecomment-171349872
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MobleyLab/alchemical-analysis/issues/66#issuecomment-171412434>
> .
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436

**Comment by halx** [comment]
What I have in mind is that the K times K matrix of energies needs to be
extrapolated to a (K+2) times (K+2) matrix (2 because of the missing end
points).  The KxK matrix will be centered within the (K+2)x(K+2) matrix.
So I will have to extrapolate each row and column both horizontally and
vertically to the left/right/top/bottom to get estimates along the edges.
These edges will finally need to serve for the extrapolation to obtain the
corners.  In my scheme I will have to decide what functions to use for
approximating each row and column vector of points (probably splines).  I
was thinking that the local curvature near the extrapolated points would
give some information about the quality of the fit.  But of course I could
just look at how the approximated spline points deviate from the real ones.

Any other suggestions?

**Comment by davidlmobley** [comment]
This sounds like it would be something @mrshirts would be interested in. But I don't particularly have any insight. It's clearly going to need some testing and might be publishable as a short note somewhere. 

Probably GROMACS would be a good place to test this, in that what you want to do is run a setup LIKE AMBER but where you can actually run at the endpoints, and then drop the endpoints and extrapolate and compare with what you get if you don't drop the endpoints.

**Comment by mrshirts** [comment]
I think extrapolating the energies by splining is very complicated, and can easily lead to errors. 

For linear energies (say, turning off charges), then calculating the precise energies (up to roundoff error) is very straightforward at unsampled states, and can be done by some linear algebra.  This might be worth doing.  However, I don't want to put in any uncontrolled approximation for the endpoint energies in an automated code.  Remember that error is exponential - if one configuration goes to low in energy, then it contributes with weight exp(-Beta U).  It's safer to extrapolate the final free energy curve (if you're at lambda 0.99, for example, and also have points at 0.98, 0.97) since then the error will be linear. If you extrapolate the energies, you will get compounded error.   What if someone simulates up to lambda 0.8, then tries to extrapolate?  It would be really bad.

Also, you only need to fill in a K x (K+2) matrix, since you only need to calculate the energies of unsampled states at the sampled states, not visa versa. So no corners.

Ditto on AMBER not sampling endstates. . . .

**Comment by davidlmobley** [comment]
Yes, I agree with this. Extrapolating energies is going to be too sketchy
and in all likelihood they will be too noisy. The best thing to do is
extrapolate the free energy curve, and we'll need some way to decide how
big an extrapolation is too big (automatically). Michael, any thoughts on
how to do this?

Thanks.


On Fri, Jan 15, 2016 at 9:44 AM, Michael Shirts <notifications@github.com>
wrote:

> I think extrapolating the energies by splining is very complicated, and
> can easily lead to errors.
>
> For linear energies (say, turning off charges), then calculating the
> precise energies (up to roundoff error) is very straightforward at
> unsampled states, and can be done by some linear algebra. This might be
> worth doing. However, I don't want to put in any uncontrolled approximation
> for the endpoint energies in an automated code. Remember that error is
> exponential - if one configuration goes to low in energy, then it
> contributes with weight exp(-Beta U). It's safer to extrapolate the final
> free energy curve (if you're at lambda 0.99, for example, and also have
> points at 0.98, 0.97) since then the error will be linear. If you
> extrapolate the energies, you will get compounded error. What if someone
> simulates up to lambda 0.8, then tries to extrapolate? It would be really
> bad.
>
> Also, you only need to fill in a K x (K+2) matrix, since you only need to
> calculate the energies of unsampled states at the sampled states, not visa
> versa. So no corners.
>
> Ditto on AMBER not sampling endstates. . . .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MobleyLab/alchemical-analysis/issues/66#issuecomment-172030524>
> .
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436

**Comment by halx** [comment]
Many thanks for all the input.

My idea is not to have this switched on by default but rather have the user
do this with an explicit command line option.  Of course, quality control
must still be there. Extrapolation of the final free energy curve sounds
indeed like the better plan.

**Comment by mrshirts** [comment]
I think that any sort of extrapolation is a bad idea.  It's new functionality that allows users to cut off their own feet. The error analysis gets to be really horrific. There's really no good reason to extrapolate in a generally distributed code.

**Comment by davidlmobley** [comment]
OK, since we're in agreement I'll mark this as closed and plan on not doing it unless someone comes back with a compelling argument to the contrary. Thanks.
