### ISSUE TITLE
Problem with pymbar API; issues with cubic spline interpolation in TI

### ISSUE THREAD

**Issue by driesvr** [MobleyLab/alchemical-analysis#69]
Hi,

I'm experiencing the following error when I try to calculate the overlap matrix:

  File "/Users/dvr/Documents/Cheminformatics_tools/alchemical-analysis-master/alchemical_analysis/alchemical_analysis.py", line 1226, in <module>
    main()
  File "/Users/dvr/Documents/Cheminformatics_tools/alchemical-analysis-master/alchemical_analysis/alchemical_analysis.py", line 1202, in main
    Deltaf_ij, dDeltaf_ij = estimatewithMBAR(u_kln, N_k, P.relative_tolerance, regular_estimate=True)
  File "/Users/dvr/Documents/Cheminformatics_tools/alchemical-analysis-master/alchemical_analysis/alchemical_analysis.py", line 292, in estimatewithMBAR
    O = MBAR.computeOverlap()[2]
IndexError: invalid index to scalar variable.

My files can be found at https://www.dropbox.com/sh/sobp5423rm0ubog/AAAmrsxBLSXQVoein7ue9lZTa?dl=0. The command I'm using is: python ~/Documents/Cheminformatics_tools/alchemical-analysis-master/alchemical_analysis/alchemical_analysis.py -q xvg -p md -u kJ -c -t 300 -w. 

This is only a prototype run to check if my lambda spacing is sufficient, hence the short simulations. The cfm.pdf looks weird as well, though I suppose that could be related to the length of the simulations. This is the first step in my simulation, ie. removing the coulombic interactions for a hydrogen atom.
Kind regards

Dries

**Comment by davidlmobley** [comment]
I think you may be using an older version of pymbar. Can you check what
version you are using, or that you are using the latest version?

Pymbar changed the number of return arguments from MBAR a while back.

Thanks.

On Fri, Jan 22, 2016 at 5:38 AM, Dries VR <notifications@github.com> wrote:

> Hi,
>
> I'm experiencing the following error when I try to calculate the overlap
> matrix:
>
> File
> "/Users/dvr/Documents/Cheminformatics_tools/alchemical-analysis-master/alchemical_analysis/alchemical_analysis.py",
> line 1226, in
> main()
> File
> "/Users/dvr/Documents/Cheminformatics_tools/alchemical-analysis-master/alchemical_analysis/alchemical_analysis.py",
> line 1202, in main
> Deltaf_ij, dDeltaf_ij = estimatewithMBAR(u_kln, N_k, P.relative_tolerance,
> regular_estimate=True)
> File
> "/Users/dvr/Documents/Cheminformatics_tools/alchemical-analysis-master/alchemical_analysis/alchemical_analysis.py",
> line 292, in estimatewithMBAR
> O = MBAR.computeOverlap()[2]
> IndexError: invalid index to scalar variable.
>
> My files can be found at
> https://www.dropbox.com/sh/sobp5423rm0ubog/AAAmrsxBLSXQVoein7ue9lZTa?dl=0.
>
> This is only a prototype run to check if my lambda spacing is sufficient,
> hence the short simulations. The cfm.pdf looks weird as well, though I
> suppose that could be related to the length of the simulations. This is the
> first step in my simulation, ie. removing the coulombic interactions for a
> hydrogen atom.
>
> Kind regards
>
> Dries
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MobleyLab/alchemical-analysis/issues/69>.
>



-- 
David Mobley
Associate Professor
Department of Pharmaceutical Sciences
Department of Chemistry
3134B Natural Sciences I
University of California, Irvine
Irvine, CA 92697
dmobley@uci.edu
work (949) 824-6383
cell (949) 385-2436

**Comment by driesvr** [comment]
I was using the version from pip - upgrading to the master fixed my problem. Thanks. It might be a decent idea to perform a quick version check to ensure that the user's version is up to date.
I'm also getting an error when I try to plot the TI figure, even with the newest pymbar version:

Plotting the TI figure...
Traceback (most recent call last):
  File "../alchemical-analysis-master/alchemical_analysis/alchemical_analysis.py", line 1226, in <module>
    main()
  File "../alchemical-analysis-master/alchemical_analysis/alchemical_analysis.py", line 1218, in main
    plotdFvsLambda()
  File "../alchemical-analysis-master/alchemical_analysis/alchemical_analysis.py", line 1012, in plotdFvsLambda
    plotTI()
  File "../alchemical-analysis-master/alchemical_analysis/alchemical_analysis.py", line 934, in plotTI
    ynew = cubspl[j].interpolate(y, xnew)
AttributeError: 'int' object has no attribute 'interpolate'

Thanks for your help.

**Comment by davidlmobley** [comment]
Yes, looks like we need to add a version check for that.

I'll have to look into the 'interpolate' issue. Thanks.

On Fri, Jan 22, 2016 at 12:07 PM, Dries VR <notifications@github.com> wrote:

> I was using the version from pip - upgrading to the master fixed my
> problem. Thanks. It might be a decent idea to perform a quick version check
> to ensure that the user's version is up to date.
> I'm also getting an error when I try to plot the TI figure, even with the
> newest pymbar version:
>
> Plotting the TI figure...
> Traceback (most recent call last):
> File
> "../alchemical-analysis-master/alchemical_analysis/alchemical_analysis.py",
> line 1226, in
> main()
> File
> "../alchemical-analysis-master/alchemical_analysis/alchemical_analysis.py",
> line 1218, in main
> plotdFvsLambda()
> File
> "../alchemical-analysis-master/alchemical_analysis/alchemical_analysis.py",
> line 1012, in plotdFvsLambda
> plotTI()
> File
> "../alchemical-analysis-master/alchemical_analysis/alchemical_analysis.py",
> line 934, in plotTI
> ynew = cubspl[j].interpolate(y, xnew)
> AttributeError: 'int' object has no attribute 'interpolate'
>
> Thanks for your help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MobleyLab/alchemical-analysis/issues/69#issuecomment-174032734>
> .
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436

**Comment by davidlmobley** [comment]
I added the version check but still need to deal with the cubic spline interpolation issue.

**Comment by MatteoA** [comment]
Hi David, are there other known issues related to using pymbar versions older than 3.0.0, apart from the MBAR.computerOverlap()[2] problem? 

I too have been using the pip version (v2.1.0) as it seems the most straightforward way to install external packages into the Canopy environment. I changed MBAR.computerOverlap()[2] to MBAR.computeOverlap(output='matrix') in alchemical-analysis to make it compatible with the older pymbar version, but I now wonder whether there are other more fundamental issues I am not aware of that might have affected the results computed with the older pymbar version.

**Comment by halx** [comment]
Matteo,

I really think you should bite the bullet and make all effort to update to
the latest Pymbar version.  Pavel and David may not have made note of all
the changes that were necessary to upgrade to the new version and what it
would mean to use an older version instead.  So you may very well be on a
track of incremental fixes and/or, worse, there _could_ (not saying that
there are) subtle differences cropping up that simply give you wrong
results without noticing it.  It's just not worth it to hunt down any such
issues.  Safest assumption now is that the new version of the analysis tool
firmly relies on Pymbar 3.0.0.  That's also where all the testing is
happening.

Cheers,
Hannes.

**Comment by MatteoA** [comment]
Hi Hannes, thanks for the fast reply, I will indeed update to the latest pymbar asap. I will probably double check the results match what I obtained with the older version just to be sure. I also just noticed David requested an update of the pymbar version on PyPI, which would indeed be useful. Many thanks for all your help.

**Comment by davidlmobley** [comment]
You could also just switch to using conda for installing... :)

I'm not aware of other issues with older pymbar versions, but I do
recommend updating.

**Comment by MatteoA** [comment]
Thanks for the tip! I have been thinking about switching to conda for a while actually, but I haven't done it simply due to inertia, now it might be the time...

**Comment by davidlmobley** [comment]
Ha, yes. It's sort of magical. Once you configure the omnia channel it's
basically just matter of:
conda install pymbar
Then download and install alchemical-analysis. (On the to-do list: Make
alchemical-analysis conda-installable).

DM


On Wed, Feb 3, 2016 at 6:58 AM, Matteo Aldeghi <notifications@github.com>
wrote:

> Thanks for the tip! I have been thinking about switching to conda for a
> while actually, but I haven't done it simply due to inertia, now it might
> be the time...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MobleyLab/alchemical-analysis/issues/69#issuecomment-179277056>
> .
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436

**Comment by davidlmobley** [comment]
@driesvr - should be resolved by #76 ; can you check?

**Comment by driesvr** [comment]
Yup, looks like everything's working here as well. Thanks!
