### ISSUE TITLE
Lambda index out of bounds when accumulating free energies

### ISSUE THREAD

**Issue by driesvr** [MobleyLab/alchemical-analysis#70]
Hi,

I'm getting the following error when I use alchemical-analysis for the second part of my run (bonded, LJ and masses). 

  File "/Users/dvr/Work/alchemical-analysis-master/alchemical_analysis/alchemical_analysis.py", line 1226, in <module>
    main()
  File "/Users/dvr/Work/alchemical-analysis-master/alchemical_analysis/alchemical_analysis.py", line 1212, in main
    totalEnergies()
  File "/Users/dvr/Work/alchemical-analysis-master/alchemical_analysis/alchemical_analysis.py", line 583, in totalEnergies
    dF[name] += df_allk[k][name]
IndexError: index out of bounds

Everything works fine for the first and third part of the transformation with the same alchemical-analysis version and settings. Detailed output and input files can be found here:
https://www.dropbox.com/sh/vmjh7rmswbg0bd8/AADUpt8622PBUnxill6eOoIma?dl=0

Kind regards

Dries

**Comment by davidlmobley** [comment]
Thanks. I'm guessing this is somewhat related to
https://github.com/MobleyLab/alchemical-analysis/issues/65 in that we've
probably not tested this with the same number of or distribution of lambda
components that you're using. Hopefully the fix will be simple, though as
the other issue notes there are more long-range planning issues to deal
with.

Sorry for the delay here. I'm swamped in the first part of the week so it
may take me til late this week to get a look at it.

On Sun, Jan 24, 2016 at 4:10 AM, Dries VR <notifications@github.com> wrote:

> Hi,
>
> I'm getting the following error when I use alchemical-analysis for the
> second part of my run (bonded, LJ and masses).
>
> File
> "/Users/dvr/Work/alchemical-analysis-master/alchemical_analysis/alchemical_analysis.py",
> line 1226, in
> main()
> File
> "/Users/dvr/Work/alchemical-analysis-master/alchemical_analysis/alchemical_analysis.py",
> line 1212, in main
> totalEnergies()
> File
> "/Users/dvr/Work/alchemical-analysis-master/alchemical_analysis/alchemical_analysis.py",
> line 583, in totalEnergies
> dF[name] += df_allk[k][name]
> IndexError: index out of bounds
>
> Everything works fine for the first and third part of the transformation
> with the same alchemical-analysis version and settings. Detailed output and
> input files can be found here:
> https://www.dropbox.com/sh/vmjh7rmswbg0bd8/AADUpt8622PBUnxill6eOoIma?dl=0
>
> Kind regards
>
> Dries
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MobleyLab/alchemical-analysis/issues/70>.
>



-- 
David Mobley
Associate Professor
Department of Pharmaceutical Sciences
Department of Chemistry
3134B Natural Sciences I
University of California, Irvine
Irvine, CA 92697
dmobley@uci.edu
work (949) 824-6383
cell (949) 385-2436

**Comment by davidlmobley** [comment]
Investigating this now. It could be it is also related to #64 .

**Comment by davidlmobley** [comment]
This should be resolved by #72 . Can you test that it works for you? 

You may also want to read #65 , as there is a larger enhancement we need to make to make the code report the correct labels for different lambda components in cases where you're not doing just a simple consecutive Coulomb-then-van-der-Waals transformation, as you aren't here. But at least now things should work.

**Comment by driesvr** [comment]
Hi, just tested the patch and it looks like everything's working. 
Thanks.

#65 looks like a very interesting enhancement, it would be nice to see the contribution of various terms. 

As everything's working on my end, I'll go ahead and close this issue. I'd be happy to help if you require any further testing though.
