### ISSUE TITLE
Error in Reading GROMACS dhdl.xvg with NumPy v1.10

### ISSUE THREAD

**Issue by jtp4kc** [MobleyLab/alchemical-analysis#84]
Hello:

I have used alchemical_analysis.py in the past successfully to estimate MBAR free energy differences between states. Thank you for making this tool available for open use.

I recently updated NumPy to version 1.10. In trying to use alchemical_analysis.py on a GROMACS dhdl.xvg, I received the following error:

>   File "~/git/alchemical-analysis/alchemical_analysis/parser_gromacs.py", line 302, in readDataGromacs
>     extract_states  = numpy.genfromtxt(f.filename, dtype=int, skiprows=f.skip_lines, skip_footer=1*bLenConsistency, usecols=1)
> TypeError: genfromtxt() got an unexpected keyword argument 'skiprows'

Looking at the NumPy documentation at [http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.genfromtxt.html](http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.genfromtxt.html),

> numpy.genfromtxt
> 
> numpy.**genfromtxt**(...)
> Load data from a text file, with missing values handled as specified.
> 
> **Parameters**:	
> **skiprows**: _int, optional_
> skiprows was removed in numpy 1.10. Please use skip_header instead.
> **skip_header**: _int, optional_
> The number of lines to skip at the beginning of the file.

In parser_gromacs.py, the following change of line 302 fixes the present issue:
`         extract_states  = numpy.genfromtxt(f.filename, dtype=int, skip_header=f.skip_lines, skip_footer=1*bLenConsistency, usecols=1)`

This may not be all the changes due to NumPy v1.10, but it does in this case allow the code to progress farther. I run into another issue, which may not be related to the NumPy update.
After the change for a single .xvg, I incur the following error:

>   File "~/git/alchemical-analysis/alchemical_analysis/parser_gromacs.py", line 126, in slice_data
>     dhdlt[state, :, nsnapshots_l[state]:nsnapshots_r[state]] = data[read_dhdl_sta : read_dhdl_end, :]
> ValueError: could not broadcast input array from shape (3,1808) into shape (3,10001)

I'm not entirely sure why this error occurs. I've only seen broadcasting errors like this in trying to run multiple .xvgs which are not each from a unique state (Related to now-closed issue **_multiple expanded ensemble files not working #36_**). There are 10001 data points in the xvg, and I presume the 3 is from the three dhdl potential types fep, coul, and vdw. 1808 appears to be how many samples are in state 0. Just listing the details here in case this error _is_ related to the NumPy version.

Each of these errors (genfromtxt TypeError and dhdlt ValueError) were repeated after pulling the latest version of the master branch (immediately before posting this issue). The specific NumPy version is 1.10.4-py27_0, installed by conda. 

I'm not sure if there is an intent to keep up with newer versions of NumPy, but I wanted to make a note of the error, in case it helps.

Thank you for your time.

**Comment by limn1** [comment]
Hello jtp4kc,
Could you provide your input data so I could replicate the ValueError you are seeing? The numpy.genfromtxt issue is easily resolvable. I can submit a PR for it after looking into the other error you are experiencing.

**Comment by jtp4kc** [comment]
Sure.

I have attached the input .xvg file [benzene-equil4-00.xvg](https://github.com/MobleyLab/alchemical-analysis/files/175547/benzene-equil4-00.txt). Please note that the file extension has been changed to .txt, as GitHub did not understand how to treat an .xvg file.

On the command line (in a bash shell), I type:
`python ~/git/alchemical-analysis/alchemical_analysis/alchemical_analysis.py -p "benzene-equil4-00" -r 8 -t 300 -u kBT -v -w -x &> alchem.out`

Please let me know if you need any more information.

Thank you.

**Comment by limn1** [comment]
This problem might be better suited for @FEPanalysis since it appears related to issue #36 and I'm not familiar with multiple expanded ensemble files.

**Comment by bioSandMan** [comment]
Has this been resolved? I'm getting the same error with an alchemical simulation using Gromacs, fep-lambdas and/or using coul-lambdas along with vdw-lambdas. Here is the output

Started on Sat May 14 11:45:18 2016
Command line was: /mnt/home/cmira/alchemical-analysis/alchemical_analysis/alchemical_analysis.py -t 300 -x -v -w -p prod

Checking for corrupted xvg files....
No corrupt lines found, no data was removed from ./prod.lxvg
Reading metadata from ./prod.lxvg...
Temperature is 300 K.
First 0 ps (0 snapshots) will be discarded due to equilibration from file ./prod.lxvg...
Loading in data from ./prod.lxvg (all states) ...
Traceback (most recent call last):
  File "/mnt/home/cmira/alchemical-analysis/alchemical_analysis/alchemical_analysis.py", line 1276, in <module>
    main()
  File "/mnt/home/cmira/alchemical-analysis/alchemical_analysis/alchemical_analysis.py", line 1207, in main
    nsnapshots, lv, dhdlt, u_klt = parser_gromacs.readDataGromacs(P)
  File "/mnt/gfs/cmira/alchemical-analysis/alchemical_analysis/parser_gromacs.py", line 324, in readDataGromacs
    f.iter_loadtxt(nf)
  File "/mnt/gfs/cmira/alchemical-analysis/alchemical_analysis/parser_gromacs.py", line 152, in iter_loadtxt
    slice_data(data_k, k)
  File "/mnt/gfs/cmira/alchemical-analysis/alchemical_analysis/parser_gromacs.py", line 126, in slice_data
    dhdlt[state, :, nsnapshots_l[state]:nsnapshots_r[state]] = data[read_dhdl_sta : read_dhdl_end, :]
ValueError: could not broadcast input array from shape (2,52505) into shape (2,500001)


I also have an older version of pymbar, where I still have the examples folder. I get the same error. I have numpy 1.10.4, also conda.

**Comment by davidlmobley** [comment]
Not resolved yet, but this suggests that the issue is not one relating to
numpy versions, so I'll try to get it looked at sooner. Apologies for the
delay - we don't currently have someone doing much development on this as
the student involved graduated, so it's been hard to get to this issue.
We'll try to do so soon.

Thanks.


On Sat, May 14, 2016 at 2:54 PM, Christopher Mirabzadeh <
notifications@github.com> wrote:

> Has this been resolved? I'm getting the same error with an alchemical
> simulation using Gromacs, fep-lambdas and/or using coul-lambdas along with
> vdw-lambdas. Here is the output
>
> Started on Sat May 14 11:45:18 2016
> Command line was:
> /mnt/home/cmira/alchemical-analysis/alchemical_analysis/alchemical_analysis.py
> -t 300 -x -v -w -p prod
>
> Checking for corrupted xvg files....
> No corrupt lines found, no data was removed from ./prod.lxvg
> Reading metadata from ./prod.lxvg...
> Temperature is 300 K.
> First 0 ps (0 snapshots) will be discarded due to equilibration from file
> ./prod.lxvg...
> Loading in data from ./prod.lxvg (all states) ...
> Traceback (most recent call last):
> File
> "/mnt/home/cmira/alchemical-analysis/alchemical_analysis/alchemical_analysis.py",
> line 1276, in
> main()
> File
> "/mnt/home/cmira/alchemical-analysis/alchemical_analysis/alchemical_analysis.py",
> line 1207, in main
> nsnapshots, lv, dhdlt, u_klt = parser_gromacs.readDataGromacs(P)
> File
> "/mnt/gfs/cmira/alchemical-analysis/alchemical_analysis/parser_gromacs.py",
> line 324, in readDataGromacs
> f.iter_loadtxt(nf)
> File
> "/mnt/gfs/cmira/alchemical-analysis/alchemical_analysis/parser_gromacs.py",
> line 152, in iter_loadtxt
> slice_data(data_k, k)
> File
> "/mnt/gfs/cmira/alchemical-analysis/alchemical_analysis/parser_gromacs.py",
> line 126, in slice_data
> dhdlt[state, :, nsnapshots_l[state]:nsnapshots_r[state]] =
> data[read_dhdl_sta : read_dhdl_end, :]
> ValueError: could not broadcast input array from shape (2,52505) into
> shape (2,500001)
>
> I also have an older version of pymbar, where I still have the examples
> folder. I get the same error. I have numpy 1.10.4, also conda.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/MobleyLab/alchemical-analysis/issues/84#issuecomment-219237041>
>



-- 
David Mobley
Associate Professor
Department of Pharmaceutical Sciences
Department of Chemistry
3134B Natural Sciences I
University of California, Irvine
Irvine, CA 92697
dmobley@uci.edu
work (949) 824-6383
cell (949) 385-2436

**Comment by bioSandMan** [comment]
I actually tried different version of numpy using "conda install numpy=VersionNumber" all the way down to 1.7 and none of that resolved the issue. I'm thinking of doing a clean install of python in a screen session and seeing if my older version of pymbar works.That would at least tell us for sure that it's not numpy. I'll see if I can test that this week.

**Comment by mrshirts** [comment]
Someone reported having an issues with this, where the numpy version did seem to be the issue (they were using 1.11). I will report if downgrading helps them solve the issue.

**Comment by g-bauer** [comment]
Hi everybody,

I think i found the issue. Within the dhdl.xvg, states are stored as `float`. In parser_gromacs.py [here](https://github.com/MobleyLab/alchemical-analysis/blob/11c02a1f60d135c243f93044ee264141fe9ed2e1/alchemical_analysis/parser_gromacs.py#L302) the number of snapshots are read in as `int` (i.e. it will read all states as `-1`) which will lead to wrong dimensions. The broadcast error is a consequence of this bug. Changing said line to: 

`extract_states  = numpy.genfromtxt(f.filename, dtype=float, skiprows=f.skip_lines, skip_footer=1*bLenConsistency, usecols=1)`

works for me.

**Comment by bioSandMan** [comment]
Everything seems to be working. I can’t seem to reproduce the error as before. Either there was an update or I’m doing something differently. If I come across the bug again I will try the offered fix. Thank you for your help.

-ChrisM

Mirabzadeh, Christopher
Graduate Research Assistant/Physics Instructor
Department of Physics
University of Idaho
Moscow, Id
(509)339-5647



On Sep 15, 2016, at 8:04 AM, Gernot Bauer <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi everybody,

I think i found the issue. Within the dhdl.xvg, states are stored as float. In parser_gromacs.py here<https://github.com/MobleyLab/alchemical-analysis/blob/11c02a1f60d135c243f93044ee264141fe9ed2e1/alchemical_analysis/parser_gromacs.py#L302> the number of snapshots are read in as int (i.e. it will read all states as -1) which will lead to wrong dimensions. The broadcast error is a consequence of this bug. Changing said line to:

extract_states = numpy.genfromtxt(f.filename, dtype=float, skiprows=f.skip_lines, skip_footer=1*bLenConsistency, usecols=1)

works for me.

**Comment by davidlmobley** [comment]
I'm going to mark this as closed for now since no one seems to be able to reproduce, but someone should reopen if it's still an issue.
