### ISSUE TITLE
Issue with Sorting input data by starting time (parser_amber.py)

### ISSUE THREAD

**Issue by baribefe** [MobleyLab/alchemical-analysis#86]
Hello there,

I am getting this error when I try to use alchemical_analysis.py which is coming from amber MDOUT file  parsing. I had it write out the offending variables ( found, uniq in parser_amber.py)

Command line was: ./alchemical-analysis/alchemical_analysis/alchemical_analysis.py -a AMBER -d data -p [01].*/ti00[2-9] -q out -o . -r 5 -u kcal -s 0 -g -w

Loading in data from data/0.4/ti003.out...  6000 data points, 6000 DV/DL averages
Loading in data from data/0.4/ti002.out...  6000 data points, 6000 DV/DL averages
Loading in data from data/0.7/ti003.out...  6000 data points, 6000 DV/DL averages
Loading in data from data/0.7/ti002.out...  6000 data points, 6000 DV/DL averages
Loading in data from data/0.6/ti003.out...  6000 data points, 6000 DV/DL averages
Loading in data from data/0.6/ti002.out...  6000 data points, 6000 DV/DL averages
Loading in data from data/0.0/ti003.out...  6000 data points, 6000 DV/DL averages
Loading in data from data/0.0/ti002.out...  6000 data points, 6000 DV/DL averages
Loading in data from data/0.9/ti003.out...  6000 data points, 6000 DV/DL averages
Loading in data from data/0.9/ti002.out...  6000 data points, 6000 DV/DL averages
Loading in data from data/0.2/ti003.out...  6000 data points, 6000 DV/DL averages
Loading in data from data/0.2/ti002.out...  6000 data points, 6000 DV/DL averages
Loading in data from data/0.1/ti003.out...  6000 data points, 6000 DV/DL averages
Loading in data from data/0.1/ti002.out...  6000 data points, 6000 DV/DL averages
Loading in data from data/0.5/ti003.out...  6000 data points, 6000 DV/DL averages
Loading in data from data/0.5/ti002.out...  6000 data points, 6000 DV/DL averages
Loading in data from data/0.3/ti003.out...  6000 data points, 6000 DV/DL averages
Loading in data from data/0.3/ti002.out...  6000 data points, 6000 DV/DL averages
Loading in data from data/0.8/ti003.out...  6000 data points, 6000 DV/DL averages
Loading in data from data/0.8/ti002.out...  6000 data points, 6000 DV/DL averages
Loading in data from data/1.0/ti003.out...  6000 data points, 6000 DV/DL averages
Loading in data from data/1.0/ti002.out...  6000 data points, 6000 DV/DL averages
Sorting input data by starting time
found:  [200.0, 200.0] 2 uniq:  set([200.0]) 1
ERROR: Same starting time occurs multiple times.

The header for parser_amber.py says

"Relevant namelist variables in MDIN: ntpr, ntave, ifmbar and bar*,
do NOT set t as the code depends on a correctly set begin time"

and it appears the issue stems from the begin time mentioned here. I am not exactly sure what this time it mentions here is.

Any thoughts appreciated.

Thanks!

Emmanuel

**Comment by halx** [comment]
Hi Emmanuel,

the begin time is stored in the restart file and reported also in the MDOUT
file.  The parser uses this to unambiguously reassemble the data for each
lambda. Sander/pmemd allow the user to set this time to any value through
the namelist variable 't'.  Don't do this!  Check your output files (MDOUT)
for each clambda and look for the string "begin time read from input coords
=".  They should never be the same for a given clambda.


Cheers,
Hannes.

**Comment by baribefe** [comment]
Thanks for the quick reply Hannes!
So just going into each MDOUT file (for each lambda) and chaning this to a different number should fix the problem?

Thanks again.

Emmanuel

**Comment by halx** [comment]
Yes.  The code currently only requires to find a unique set of begin times.

**Comment by davidlmobley** [comment]
Just to clarify, this is resolved?

Thanks, Hannes, for the help. I never would have guessed this was the
problem.

On Sun, Apr 3, 2016 at 11:11 PM, Hannes Loeffler <notifications@github.com>
wrote:

> Yes. The code currently only requires to find a unique set of begin times.
>
> On 3 April 2016 at 20:52, baribefe <notifications@github.com> wrote:
>
> > Thanks for the quick reply Hannes!
> > So just going into each MDOUT file (for each lambda) and chaning this to
> a
> > different number should fix the problem?
> >
> > Thanks again.
> >
> > Emmanuel
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/MobleyLab/alchemical-analysis/issues/86#issuecomment-205043328
> >
>
> >
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/MobleyLab/alchemical-analysis/issues/86#issuecomment-205149866>
>



-- 
David Mobley
Associate Professor
Department of Pharmaceutical Sciences
Department of Chemistry
3134B Natural Sciences I
University of California, Irvine
Irvine, CA 92697
dmobley@uci.edu
work (949) 824-6383
cell (949) 385-2436

**Comment by baribefe** [comment]
Yes, it is! I just made the changes and ran it again this morning.
Thanks again for your help!

Cheers,

Emmanuel

**Comment by halx** [comment]
I have just realized that pmemd16 reads the initial begin time from the restart file but then resets its own counter.  If for instance I have 500.0 ps MD runs and the initial time was, say 1000.0 ps the begin times of consecutive runs would be: 1000.0, 500.0, 1000.0, 1500.0, etc.

I think that's a silly bug (older versions got this right) and I will see what the AMBER mailing list will respond.

**Comment by halx** [comment]
Ok.  This is only an issue if the first MD run starts with irest=0 i.e. if it is not a restart run.  In a typical setup protocol where one does first do some sort of "equilibration" that is prior MD runs this is not an issue.

**Comment by baribefe** [comment]
Thanks a lot for letting me know.

Cheers,

Emmanuel
