### ISSUE TITLE
Error bar estimation

### ISSUE THREAD

**Issue by AlexanderWi** [MobleyLab/alchemical-analysis#98]
Dear all,
I am using alchemical free energy tools to calculate the relative binding free energy in Gromacs. I mainly use Thermodynamic Integration, and I was wondering how the error bar is estimated there? Which method is applied to do so? 
Thanks
Alex

**Comment by davidlmobley** [comment]
Integration is done via the trapezoid method, and it's just standard analytical error propagation of the uncertainty estimate at each lambda point into the overall free energy estimate.
